# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
#  boot.kernelParams = [ "mem_sleep_default=deep" "acpi_sleep=s3_bios" ]; 
  boot.kernelParams = [ "amd_iommu=off"  #fixed sleep not working
                                    "mem_sleep_default=s2idle"
                                    "acpi_sleep=off"
                                      #"amdgpu.gttsize=8048" # Sets GTT size to 12GB
                                       ];
  boot.extraModulePackages = [ ];

  # Set CPU frequency governor to powersave
  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = "powersave";
  # Set minimum and maximum CPU frequencies (in kHz)
  powerManagement.cpufreq.min = 400000;     # 400 MHz
  # powerManagement.cpufreq.max = 3000000;    # 3 GHz
  # sudo cpupower frequency-set -u 4372000kHz
  # sudo cpupower frequency-set -d 402000kHz -u 4372000kHz
  # sudo cpupower frequency-set -d 4372000kHz -u 4372000kHz

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3fdc0395-cd02-4cf9-9cd0-660f333e6e17";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cff2a752-96ec-4107-9490-89465c73a09e".device = "/dev/disk/by-uuid/cff2a752-96ec-4107-9490-89465c73a09e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FCC5-487C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


}

#     CPU max MHz:             4372.0000
# watch -n1 "grep \"^[c]pu MHz\" /proc/cpuinfo"

#powerManagement.enable
#powerManagement.cpufreq.min
#powerManagement.cpufreq.max
#powerManagement.cpuFreqGovernor
#Often used values: “ondemand”, “powersave”, “performance”
# [owner@nixos:~]$ lscpu
# Architecture:                x86_64
#   CPU op-mode(s):            32-bit, 64-bit
#   Address sizes:             48 bits physical, 48 bits virtual
#   Byte Order:                Little Endian
# CPU(s):                      16
#   On-line CPU(s) list:       0-15
# Vendor ID:                   AuthenticAMD
#   Model name:                AMD Ryzen 7 5700U with Radeon Graphics
#     CPU family:              23
#     Model:                   104
#     Thread(s) per core:      2
#     Core(s) per socket:      8
#     Socket(s):               1
#     Stepping:                1
#     Frequency boost:         enabled
#     CPU(s) scaling MHz:      40%
#     CPU max MHz:             4372.0000
#     CPU min MHz:             400.0000
#     BogoMIPS:                3593.50
